force-app/main/default/objects/LGF_FieldMapping__c/LGF_FieldMapping__c.object-meta.xml
<CustomObject>
    <label>【LGForce】項目マッピング</label>
    <nameField>
        <label>テンプレート項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LGF_FieldMapping__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>項目API参照名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LGF_FieldMapping__c/fields/LGF_Template__c.field-meta.xml
<CustomField>
    <fullName>LGF_Template__c</fullName>
    <label>【LGForce】テンプレート</label>
    <referenceTo>LGF_Template__c</referenceTo>
    <relationshipLabel>【LGForce】項目マッピング</relationshipLabel>
    <relationshipName>FieldMappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LGF_Template__c/LGF_Template__c.object-meta.xml
<CustomObject>
    <label>【LGForce】テンプレート</label>
    <nameField>
        <label>テンプレート名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LGF_Template__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <label>ContentDocument ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LGF_Template__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LGF_Template__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>オブジェクトAPI参照名</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LGF_FieldMappingController_Test.cls
@isTest
private class LGF_FieldMappingController_Test {

    @isTest
    static void testFieldMappings() {
        LGF_Template__c template = 
            new LGF_Template__c(
                Name = 'TEST_TEMPLATE'
                , ContentDocumentId__c = '123456789012345678'
                , ObjectApiName__c = 'Account'
                , OutputFileName__c = 'TEST_OUTPUT'
                , IsActive__c = true
            );
        insert template;

        Test.startTest();
        List<LGF_FieldMapping__c> fieldMappings;
        fieldMappings = LGF_FieldMappingController.getFieldMappings(null);
        System.assertEquals(null, fieldMappings);
        fieldMappings = LGF_FieldMappingController.getFieldMappings(template.Id);
        System.assertEquals(0, fieldMappings.size());
        LGF_FieldMappingController.deleteAndInsertFieldMappings(fieldMappings, template.Id);
        System.assertEquals(0, fieldMappings.size());
        fieldMappings.add(new LGF_FieldMapping__c(Name = 'TEST_1', FieldApiName__c = 'TEST_001', LGF_Template__c = template.Id));
        fieldMappings.add(new LGF_FieldMapping__c(Name = 'TEST_2', FieldApiName__c = 'TEST_002', LGF_Template__c = template.Id));
        LGF_FieldMappingController.deleteAndInsertFieldMappings(fieldMappings, template.Id);
        fieldMappings = LGF_FieldMappingController.getFieldMappings(template.Id);
        System.assertEquals(2, fieldMappings.size());
        try{
            fieldMappings.add(new LGF_FieldMapping__c(FieldApiName__c = 'TEST_001', LGF_Template__c = template.Id));
            LGF_FieldMappingController.deleteAndInsertFieldMappings(fieldMappings, template.Id);
            System.assert(false);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        fieldMappings.remove(fieldMappings.size() - 1);
        try{
            fieldMappings.add(new LGF_FieldMapping__c(Name = 'TEST_1', FieldApiName__c = 'TEST_001', LGF_Template__c = template.Id));
            LGF_FieldMappingController.deleteAndInsertFieldMappings(fieldMappings, template.Id);
            System.assert(false);
        }catch(Exception e){
            System.debug(e.getMessage());
        }
        Test.stopTest();
    }
}