force-app/main/default/objects/LGF_FieldMapping__c/LGF_FieldMapping__c.object-meta.xml
<CustomObject>
    <label>【LGForce】項目マッピング</label>
    <nameField>
        <label>テンプレート項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LGF_FieldMapping__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <label>項目API参照名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LGF_FieldMapping__c/fields/LGF_Template__c.field-meta.xml
<CustomField>
    <fullName>LGF_Template__c</fullName>
    <label>【LGForce】テンプレート</label>
    <referenceTo>LGF_Template__c</referenceTo>
    <relationshipLabel>【LGForce】項目マッピング</relationshipLabel>
    <relationshipName>FieldMappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LGF_Template__c/LGF_Template__c.object-meta.xml
<CustomObject>
    <label>【LGForce】テンプレート</label>
    <nameField>
        <label>テンプレート名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LGF_Template__c/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <label>ContentDocument ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LGF_Template__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LGF_Template__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>オブジェクトAPI参照名</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LGF_Action.cls
global class LGF_Action {

    private class LGFActionException extends Exception {}

    global class LGFAParam {
        @AuraEnabled
        global Id recordId { get; set; }
        @AuraEnabled
        global Id templateId { get; set; }
    }

    global class LGFAResult {
        @AuraEnabled
        global String pdfData { get; set; }
        @AuraEnabled
        global String outputFileName { get; set; }
    }

    @AuraEnabled
    global static LGFAResult convertExcelToPDF(LGFAParam param) {

        system.debug(param);
        Id recordId;
        Id templateId;
        try {
            recordId = Id.valueOf(param.recordId);
            templateId = Id.valueOf(param.templateId);
        } catch (Exception e) {
            throw new LGFActionException(Label.LGF_ERR_S001);
        }

        LGF_Template__c template;
        List<LGF_FieldMapping__c> fieldMappings;
        String versionNumber;
        Blob templateData;
        try {
            String soql = 'SELECT Id ';
            soql += ', ObjectApiName__c ';
            soql += ', ContentDocumentId__c ';
            soql += ', OutputFileName__c ';
            soql += 'FROM LGF_Template__c ';
            soql += 'WHERE IsActive__c = true ';
            soql += 'AND Id = \'' + String.escapeSingleQuotes(templateId) + '\' ';
            soql += 'ORDER BY CreatedDate DESC ';
            soql += 'LIMIT 1';
            System.debug(soql);
            List<LGF_Template__c> templates = Database.query(soql);
            template = templates[0];
            ContentDocument cd = 
                [SELECT Id
                    , LatestPublishedVersion.VersionNumber
                    , LatestPublishedVersion.VersionData
                    FROM ContentDocument
                    WHERE Id = :template.ContentDocumentId__c
                    LIMIT 1];
            versionNumber = cd.LatestPublishedVersion.VersionNumber;
            templateData = cd.LatestPublishedVersion.VersionData;
            if(templateData == null) {
                throw new LGFActionException();
            }
            fieldMappings = 
                [SELECT Id
                    , Name
                    , FieldApiName__c
                    FROM LGF_FieldMapping__c
                    WHERE LGF_Template__c = :template.Id];
        } catch (Exception e) {
            throw new LGFActionException(Label.LGF_ERR_S002);
        }

        String body;
        try {
            String soql = 'SELECT Id ';
            for(LGF_FieldMapping__c fieldMapping : fieldMappings) {
                soql += ', ' + fieldMapping.FieldApiName__c + ' ';
            }
            soql += 'FROM ' + String.escapeSingleQuotes(template.ObjectApiName__c) + ' ';
            soql += 'WHERE Id = \'' + String.escapeSingleQuotes(recordId) + '\' ';
            soql += 'LIMIT 1';
            System.debug(soql);
            List<SObject> records = Database.query(soql);
            body = '{';
            body += '"fieldMappings":' + JSON.serialize(fieldMappings) + ',';
            body += '"record":' + JSON.serialize(records[0]) + ',';
            body += '"fileName":' + JSON.serialize(template.OutputFileName__c) + ',';
            body += '"templateData":' + JSON.serialize(EncodingUtil.base64Encode(templateData)) + ',';
            body += '"organizationId":' + JSON.serialize(UserInfo.getOrganizationId()) + ',';
            body += '"apiKey":' + JSON.serialize(Label.LGF_API_KEY);
            body += '}';
            System.debug(body);
        } catch (Exception e) {
            throw new LGFActionException(Label.LGF_ERR_S003);
        }

        LGFAResult result;
        try {
            Http h = new Http();
            HttpRequest req = new HttpRequest();
            req.setEndpoint(Label.LGF_ENDPOINT_URL);
            req.setMethod('POST');
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setBody(body);
            req.setTimeout(60000);
            System.debug('callout start: ' + req);
            System.debug(req.getBody());
            HttpResponse res = h.send(req);
            System.debug('callout done: ' + res);
            if(res.getStatusCode() == 200) {
                result = (LGFAResult) JSON.deserialize(res.getBody(), LGFAResult.class);
            } else if(res.getStatusCode() == 404) {
                throw new LGFActionException(res.getBody());
            } else {
                throw new LGFActionException('An unexpected error has occurred. Status code: ' + res.getStatusCode());
            }
            System.debug(result);
        } catch (Exception e) {
            throw new LGFActionException(Label.LGF_ERR_S004 + e.getMessage());
        }

        return result;
    }
}